# Generated by Django 5.0 on 2024-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_time', models.DateTimeField(db_column='T_TIME')),
                ('t_data', models.FloatField(db_column='T_DATA')),
            ],
            options={
                'db_table': 'nombre_de_tu_tabla_existente',
                'managed': False,
            },
        ),
    ]
