# Generated by Django 5.0 on 2024-07-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro',
            table='s703_0',
        ),
    ]
